Zoinkwiz/clue-details

src/main/java/com/cluedetails/Clues.java

clues don't actually change often enough for some standardize commit names, but i figured it might be funny
related: https://togithub.com/runelite/runelite/pull/18022

update clues for 2024-07-10 game update

---

src/main/java/com/cluedetails/Clues.java

fix: Add missing catherby drawers clue

---

src/main/java/com/cluedetails/Clues.java

Added Elite clue 12073

---

src/main/java/com/cluedetails/Clues.java

Complete the ape atoll agility course

Added details for elite 12123

---

src/main/java/com/cluedetails/Clues.java

Opening issue's issues fixed in #4 .

Add medium clues 23138 and 24140

---

src/main/java/com/cluedetails/Clues.java

Adds Scorpia Dances and Complication Cecilia clues.

Added hard clues 23174 and 23175

---

src/main/java/com/cluedetails/Clues.java

Add Dorgesh-Kaan magical lamp repair to details of step.

Add details to elite clue 12119

---

src/main/java/com/cluedetails/Clues.java

Add "La Mort" Cecilia music track step
| Clue ID | Clue | Image |
|--------|--------|--------|
| 23179 | Music: _La Mort_ | <details><summary>Clue Image</summary>![image](https://github.com/user-attachments/assets/5cae3456-b8d4-42b3-ad9d-516f4567803b)</details> |

Add hard 23179

---

src/main/java/com/cluedetails/Clues.java

Pointed out in the wiki discord that 26943 didn't have a page, I followed up and mentioned that none of the Cecilia steps had pages, and thankfully Wolaznik added all the pages for her steps.

Add all the missing Cecilia clues

---

src/main/java/com/cluedetails/ClueDetailsConfig.java
src/main/java/com/cluedetails/ClueDetailsTagsOverlay.java

feat: Additional clue tag configs

---

src/main/java/com/cluedetails/ClueDetailsPlugin.java
src/main/java/com/cluedetails/panels/ClueSelectLabel.java

feat: Edit clues via sidebar; Prepopulate edit via right click

---

src/main/java/com/cluedetails/ClueDetailsConfig.java
src/main/java/com/cluedetails/ClueDetailsOverlay.java

feat: Ability to hide tooltips

---

build.gradle

Prep for merge into Plugin Hub

Update to version 1.2.0

---

src/main/java/com/cluedetails/Clues.java

https://oldschool.runescape.wiki/w/RuneScape:Cache/2024/225.2#New_Items

feat: Add Varlamore Part 2 steps

---

src/main/java/com/cluedetails/ClueDetailsOverlay.java

This should mean less processing every frame, and also makes it more reliable for when items on the floor change whilst a menu is still open, resulting in a desync.

fix: update clue text on menu opened

---

src/main/java/com/cluedetails/BeginnerMasterClueText.java

Using https://docs.google.com/spreadsheets/d/1tmSPxJiT3YuCfpezEIS5SAyRaZjBwUaaeAd711bEPKI/edit?gid=803010595#gid=803010595 to validate

fix: Beginner Clue Text

---

src/main/java/com/cluedetails/ClueInventoryManager.java

From testing he's been consistently 8638 for me.

fix: Corrected Uri beginner ID

---

src/main/java/com/cluedetails/Clues.java

https://oldschool.runescape.wiki/w/Clue_scroll_(elite)_-_Cirr_Jad#Changes
Set coordinate to fastest location

21524 made obtainable

---

README.md
src/main/java/com/cluedetails/ClueDetailsConfig.java
src/main/java/com/cluedetails/ClueDetailsOverlay.java
src/main/java/com/cluedetails/ClueDetailsPlugin.java
src/main/java/com/cluedetails/ClueDetailsSharingManager.java
src/main/java/com/cluedetails/ClueDetailsTagsOverlay.java
src/main/java/com/cluedetails/ClueDetailsWidgetOverlay.java
src/main/java/com/cluedetails/ClueIdToDetails.java
src/main/java/com/cluedetails/ClueInstance.java
src/main/java/com/cluedetails/Clues.java
src/main/java/com/cluedetails/ThreeStepCrypticClue.java
src/main/java/com/cluedetails/panels/ClueDetailsParentPanel.java
src/main/java/com/cluedetails/panels/ClueTableCellRenderer.java

[i.imgur.com/sp9tpmQ.mp4](https://i.imgur.com/sp9tpmQ.mp4)

feat: Support Clue Details Colors

---

README.md
src/main/java/com/cluedetails/ClueDetailsWidgetOverlay.java
src/main/java/com/cluedetails/ClueInventoryManager.java

This PR does a big of breaking up of the menu entry code, and allows for item highlighting for items associated with beginner and master clues.

Add edit color and item to all clues

---

src/main/java/com/cluedetails/ClueInventoryManager.java

Need to double check we don't need non clue items stored in trackedCluesInInventory.

fix: Ensure clue details option on items hidden if no clues

---

src/main/java/com/cluedetails/ClueDetailsOverlay.java

1. Ground item regex now accounts for quantity
2. TODO: https://github.com/runelite/plugin-hub/pull/7254#issuecomment-2613733093

Ground Item Pattern Cleanup

---

src/main/java/com/cluedetails/ClueInventoryManager.java

Only clues from the ground were being tracked
https://i.imgur.com/AY9T4ks.mp4

fix: Allowed clues in inventory to still be tracked

---

src/main/java/com/cluedetails/ClueDetailsInventoryOverlay.java
src/main/java/com/cluedetails/ClueDetailsItemsOverlay.java
src/main/java/com/cluedetails/ClueDetailsPlugin.java

- Separate inventory and items overlay classes
- Items overlay needs to be dynamic, was incorrectly applied to inventory overlay
- Update inventory overlay render priority

Fix inventory overlay rendering

---

src/main/java/com/cluedetails/panels/ClueDetailsParentPanel.java

Used setComponentPopupMenu in sidebar to improve behavior of popup menus. Previously the popups in the sidebar opened before the right mouse button is released, which caused awkward behavior if mouse button was released above one of the menu options
- **Old behavior**: Here the right mouse button is released after the menu is opened
- ![Image](https://github.com/user-attachments/assets/17fe5921-0606-489d-ae57-e3cb5ed79b35)
- **New behavior**: This action would require 2 separate clicks
Inventory Setups plugin was referenced for implementation

Improved sidebar popup menu behavior

---

src/main/java/com/cluedetails/ClueDetailsPlugin.java
src/main/java/com/cluedetails/ClueGroundTimer.java

Update ClueGroundTimer duration when tiers are toggled
Use correct time values to populate Timer text

Small Clue Ground Timers fixes

---

src/main/java/com/cluedetails/ClueDetailsConfig.java
src/main/java/com/cluedetails/ClueDetailsItemsOverlay.java
src/main/java/com/cluedetails/ClueDetailsPlugin.java
src/main/java/com/cluedetails/ClueGroundOverlay.java
src/main/java/com/cluedetails/ClueInstance.java
src/main/java/com/cluedetails/ClueThreeStepSaver.java
src/main/java/com/cluedetails/ClueThreeStepSaverWidgetOverlay.java

Add ability to save a three-step master clue you wish never to complete.

feat: Three-stepper saving

---

src/main/java/com/cluedetails/ClueDetailsSharingManager.java

fix gson usage

---

src/main/java/com/cluedetails/Clues.java

https://oldschool.runescape.wiki/w/Clue_scroll_(medium)_-_EEK_ZERO_OP#Changes

fix: 2846 Ardougne Zoo challenge answer

---

src/main/java/com/cluedetails/panels/ClueDetailsParentPanel.java

fix: Sidebar filter dropdowns match config

---

src/main/java/com/cluedetails/ClueGroundSaveDataManager.java

fix: Offset saved despawn times by current client tick count
