src/main/java/com/cluedetails/Clues.java
Adds "Subterranea", "Little Cave of Horros", and "Fossilised" Cecilia music track steps for hard clues as well as the search the crate in the Lumber Yard step for hard clues
| Clue ID | Clue | Image |
|--------|--------|--------|
| 2722 | Crate: Lumber Yard | <details><summary>Clue Image</summary>![image](https://i.imgur.com/2bIczIz.png)</details> |
| 23176 | Music: _Subterranea_ | <details><summary>Clue Image</summary>![image](https://i.imgur.com/H4fvoOy.png)</details> |
| 23177 | Music: _Little Cave of Horrors_ | <details><summary>Clue Image</summary>![image](https://i.imgur.com/TVfv2tP.png)</details> |
| 23180 | Music: _Fossilised_ | <details><summary>Clue Image</summary>![image](https://i.imgur.com/WTTv6FR.png)</details> |
| 23181 | Music: _Hells Bells_ | <details><summary>Clue …
=> Add hard clues 2722, 23176, 23177, 23180

src/main/java/com/cluedetails/ClueDetailsOverlay.java, src/main/java/com/cluedetails/ClueDetailsPanel.java, src/main/java/com/cluedetails/ClueDetailsPlugin.java, src/main/java/com/cluedetails/Clues.java, src/main/java/com/cluedetails/panels/ClueDetailsParentPanel.java, src/main/java/com/cluedetails/panels/ClueSelectLabel.java
This adds personalised text for clues, which can be set by right-clicking a clue in the sidebar.
https://github.com/user-attachments/assets/3de77af3-4f79-4cf3-b5ff-6725203ca526
=> feat: Allow personalised text on clues

src/main/java/com/cluedetails/panels/ClueDetailsParentPanel.java
Adds a clue's ID to the search terms, to make it easier to find specific clues by ID.
=> feat: Added clue IDs to clue keywords for search

src/main/java/com/cluedetails/ClueDetailsConfig.java, src/main/java/com/cluedetails/ClueDetailsOverlay.java
This adds an optional toggle for whether to replace clue text with the clue hints.
=> feat: Allow clue text to be changed to hint info

src/main/java/com/cluedetails/ClueDetailsConfig.java, src/main/java/com/cluedetails/ClueDetailsPlugin.java, src/main/java/com/cluedetails/ClueDetailsTagsOverlay.java, src/main/java/com/cluedetails/panels/ClueSelectLabel.java
- Currently when the toggle is enabled, clue-details-text is automatically split based on the first ": ". This is to ensure compatibility with the old style of custom item tags, however this could be modified or made configurable.
- Currently the item tags are automatically rendered at the top of the clue if no split is applied
=> feat: Added item tags, edit via inventory toggle, config cleanup

src/main/java/com/cluedetails/ClueDetailsOverlay.java
If the overlay would overflow off the screen, it will now be placed on the left rather than the right.
=> fix: Adds dynamic placement of menu hover overlay

src/main/java/com/cluedetails/ClueDetailsOverlay.java
Don't show hover text when the information is already present on the screen.
=> feat: Conditional hover text

src/main/java/com/cluedetails/ClueDetailsPlugin.java, src/main/java/com/cluedetails/ClueGroundManager.java, src/main/java/com/cluedetails/ClueInstance.java
Issue arose where an item on the tile would be assigned a tileItem in the looping checking them, which'd then throw off its relative despawn time.
=> fix: ensure stored data for tile despawn comparisons used

src/main/java/com/cluedetails/ClueDetailsOverlay.java
- Items which share an id with the fake beginner & master clue IDs are being highlighted when those clues are marked
- Fire rune: ![image](https://github.com/user-attachments/assets/19668db0-88eb-457d-8604-d6095f7b26b8)
- Beginner & Master Clues are not able to be properly marked - TODO added
- Outlining marked clues also outlines other items in the same tile - TODO added
- Coins: ![image](https://i.imgur.com/JZyZCBc.gif)
=> fix: Fake beginner & master IDs outlined incorrectly

README.md, build.gradle, src/main/java/com/cluedetails/ClueDetailsConfig.java, src/main/java/com/cluedetails/ClueDetailsOverlay.java, src/main/java/com/cluedetails/ClueDetailsSharingManager.java, src/main/java/com/cluedetails/ClueDetailsTagsOverlay.java, src/main/java/com/cluedetails/ClueInstance.java, src/main/java/com/cluedetails/ThreeStepCrypticClue.java, src/main/java/com/cluedetails/panels/ClueDetailsParentPanel.java
Added extra right click options to export button to provide separate text and colors export
Beginner/Master right click text was incorrectly recolored w/ default value
Now correctly shows normal color if not changed by user
Cleaned up Config settings with more clear descriptions and warnings
=> 2.1.1: Separate text and colors export; fix beginner/master colors

README.md, src/main/java/com/cluedetails/ClueDetailsConfig.java, src/main/java/com/cluedetails/ClueDetailsOverlay.java, src/main/java/com/cluedetails/ClueDetailsPlugin.java, src/main/java/com/cluedetails/ClueGroundOverlay.java, src/main/java/com/cluedetails/ClueInstance.java, src/main/java/com/cluedetails/ClueInventoryManager.java
https://github.com/user-attachments/assets/f115b2d9-3f06-451a-a952-2dd76f27e2d2
- Overlay may include: text, color, despawn timers, and collapse
- Assumes the player will hide beginner and master clues in Ground Items Plugin
- Ground clues are not deprioritized when "Deprioritize menu hidden items" is enabled in Ground Items Plugin
- Fixes right click options for med keys and challenge scrolls via the addition/use of isClueItem
- Replaced instances of "Unknown, read to track" with the standard item text
- Changed ground items menu text now will also change the "Take" option text, meaning hover text is redundant in in that scenario
=> Ground Clues Overlay for Beginner & Master Clues

src/main/java/com/cluedetails/ClueDetailsOverlay.java
Ground item menu color was being inadvertently changed to white
On a fresh profile:
=> Ground item menu color fix

src/main/java/com/cluedetails/ClueDetailsOverlay.java
Hide tooltip when changeClueText enabled except for master three-step cryptic
Hover text shows additional information only for master three-step cryptic clues
=> Three-step cryptic hover text

README.md, src/main/java/com/cluedetails/ClueDetailsConfig.java, src/main/java/com/cluedetails/ClueDetailsItemsOverlay.java, src/main/java/com/cluedetails/ClueDetailsPlugin.java
Inventory tags are able to be rendered on clue scrolls and configured clue items
**If the implementation matches my intentions, only clue scrolls currently found in `cluesInInventory` should be tagged, and only items for those clues should be tagged**
Inventory tag display mode is managed by Inventory Tags plugin configuration settings
Inventory Tags plugin is allowed to draw over our Inventory tag implementation
=> Implemented inventory tags for clue scrolls and clue items

README.md, src/main/java/com/cluedetails/ClueDetailsConfig.java, src/main/java/com/cluedetails/ClueDetailsItemsOverlay.java, src/main/java/com/cluedetails/ClueDetailsTagsOverlay.java, src/main/java/com/cluedetails/ClueGroundManager.java, src/main/java/com/cluedetails/ClueGroundOverlay.java, src/main/java/com/cluedetails/ClueInstance.java, src/main/java/com/cluedetails/Clues.java
I would like to merge #101 #102 #104 first
- Tracked clues now includes all clue scrolls. Previously was limited to beginner and master clues
- This enables the expansion of the ground clues feature -- e.g. #106
- Ground clues includes configuration options including collapsing by tier or step
- ![SJWw16x](https://github.com/user-attachments/assets/d48e9742-d7d1-4a1d-8117-b60528bd50ec)
- Updated OverlayLayer to draw ground clues over the player for easier juggling
Did not notice any performance issues in my limited testing but it's possible tracking all clues causes issues not experienced while only beginners and masters were tracked
=> Easy->Elite Ground Clues Overlay

build.gradle, src/main/java/com/cluedetails/ClueDetailsConfig.java, src/main/java/com/cluedetails/ClueDetailsPlugin.java, src/main/java/com/cluedetails/ClueGroundTimer.java
Clue timers notifications behaviour should now match the following:
The oldest clue in a pile's despawn time has surpassed the configured time, and a notification has not yet been sent for that particular clue
Updating the "Timer notifications" should also trigger notifications when appropriate
Timer text color should be red when a notification has been sent
=> fix: clue timers notifications use shouldNotify

src/main/java/com/cluedetails/ClueDetailsPlugin.java, src/main/java/com/cluedetails/Clues.java
`Clues.filteredClues` list is being built on each method call and is called a lot in streams based on clue count, leading to noticable performance issues with lots of clues on the ground. This change makes the list cached and rebuilt only on startup and config changes.
Memory allocations before (see the amount of `filteredClues` calls top left, top center, top right)
After the fix (can't be noticed, a very small slice around the middle):
=> Cache filteredClues list

src/main/java/com/cluedetails/ClueBankManager.java, src/main/java/com/cluedetails/ClueDetailsInventoryOverlay.java, src/main/java/com/cluedetails/ClueDetailsItemsOverlay.java, src/main/java/com/cluedetails/ClueDetailsOverlay.java, src/main/java/com/cluedetails/ClueDetailsPlugin.java, src/main/java/com/cluedetails/ClueDetailsTagsOverlay.java, src/main/java/com/cluedetails/ClueGroundManager.java, src/main/java/com/cluedetails/ClueGroundOverlay.java, src/main/java/com/cluedetails/ClueGroundSaveDataManager.java, src/main/java/com/cluedetails/ClueGroundTimer.java, src/main/java/com/cluedetails/ClueInstance.java, src/main/java/com/cluedetails/ClueInventoryManager.java, src/main/java/com/cluedetails/Clues.java, src/main/java/com/cluedetails/WorldPointToClueInstances.java
This PR makes a few changes:
**Improved Clue Dropping Detection**
Firstly, I realised that when an item is dropped from the inventory, the onItemSpawned event will occur before the item dissapearing from the inventory. This means that if a clue is in the player's inventory and the same clue appears on the floor, and the dropped clue has the max despawn time, it must be from the inventory as you can't get drops whilst having the same tier clue.
This means we don't need to keep a track of appearing clues to later compare to the inventory state, and instead can just copy a ClueInstance from inventory when a clue appears in onItemSpawned.
Possible predicted issue: I'm unsure how this works when it comes to poor internet connections. I'd hope it still keeps the same execution order, but it …
=> fix: Improvements on ground item tracking

src/main/java/com/cluedetails/ClueDetailsPlugin.java, src/main/java/com/cluedetails/Clues.java
@TheLope noticed in https://github.com/Zoinkwiz/clue-details/pull/117#pullrequestreview-2708812499 that teleport lag was not completely fixed with master clues and with further inspection I realized that clues were constantly being searched from the cache list with loops where we could instead use maps with clue id/item id as keys.
Method calls from teleporting to crafting guild with ~60 "master clues" and away about 5 times:
Before:
After:
=> Cache clues in maps instead of a list for faster lookups

src/main/java/com/cluedetails/ClueDetailsConfig.java, src/main/java/com/cluedetails/ClueDetailsPlugin.java, src/main/java/com/cluedetails/ClueGroundOverlay.java, src/main/java/com/cluedetails/ClueGroundTimer.java
- Changed ClueGroundTimer to be an InfoBox instead of Timer
- Normalized Ground Clues Overlay and Ground Clue Timers time format to seconds
- Previously was mix of seconds & ticks
- Added renotify configuration to provide recurring notification for WorldPoints which should be notified
- This should be help by providing reminders for large stacks of clues without requiring spamming notifications as each despawn timer passes the configured threshold
=> fix: ClueGroundTimer cleanup; Add renotification

src/main/java/com/cluedetails/ClueInventoryManager.java
Stuff like blood runes was being added incorrectly for the inventory overlay.
=> fix: Add check for if clue being added to inventory store is a clue

src/main/java/com/cluedetails/ClueDetailsOverlay.java, src/main/java/com/cluedetails/ClueInstance.java
1. Ground Items "Collapse ground item menu" count was getting clobbered by menuEntry target update
- Before
- ![image](https://github.com/user-attachments/assets/5abaad0a-57c1-42cb-870b-53c130020175)
- After
- ![image](https://github.com/user-attachments/assets/7da5653b-3954-41ed-8069-b3f787529c3f)
2. "Three-step (master)" menu entries were being collapsed by Ground Items "Collapse ground item menu", meaning unique submenus could not be provided per unique three step
- Added trailing <col> tag per entry to ensure collapse doesn't apply
3. After the above changes, unidentified beginner & master clue scrolls were being incorrectly renamed due to "Collapse ground item menu"
- Only run changeGroundItemMenu when !client.isMenuOpen() to avoid conflict
=> fix: Ground Items collapse conflicts

src/main/java/com/cluedetails/ClueDetailsPlugin.java, src/main/java/com/cluedetails/ClueInventoryManager.java
Highlighted items for beginner and master steps would persist until onItemContainerChanged. This resets them after each step.
=> fix: invalidate clue items cache on new beginner or master clue

README.md, src/main/java/com/cluedetails/ClueBankManager.java, src/main/java/com/cluedetails/ClueDetailsConfig.java, src/main/java/com/cluedetails/ClueDetailsOverlay.java, src/main/java/com/cluedetails/ClueDetailsPlugin.java, src/main/java/com/cluedetails/ClueDetailsSharingManager.java, src/main/java/com/cluedetails/ClueDetailsWidgetsOverlay.java, src/main/java/com/cluedetails/ClueIdToDetails.java, src/main/java/com/cluedetails/ClueInventoryManager.java, src/main/java/com/cluedetails/CluePreferenceManager.java, src/main/java/com/cluedetails/ClueWidgetManager.java, src/main/java/com/cluedetails/Clues.java, src/main/java/com/cluedetails/WidgetId.java, src/main/java/com/cluedetails/panels/ClueDetailsParentPanel.java
Adds a new shift-click submenu to widgets to highlight them when a clue is in the inventory, same as currently supported for items.
New plugin configurations:
* Highlight clue widgets: enable widget highlighting
* Color clue widgets: use clues' colors
* Clue widgets color: the default color to use for highlighting. By default the same yellow as for items, with 50% alpha to not fully mask the widget
=> Add widget highlighting for clues

src/main/java/com/cluedetails/ClueDetailsOverlay.java, src/main/java/com/cluedetails/ClueDetailsPlugin.java, src/main/java/com/cluedetails/ClueGroundManager.java, src/main/java/com/cluedetails/ClueInstance.java, src/main/java/com/cluedetails/ClueInventoryManager.java
- fix: Track torn clues in inventory
- fix: Properly reset Clue Ground Timers
- fix: Collapse options handle unidentified beginner/master
- fix: Support changed clue text in instances
- TODO: https://github.com/Zoinkwiz/clue-details/compare/df5617db5732a6ac73994980a13ca96d5a89f006...Zoinkwiz:40598bb04c0963eac6a8cc39106e59ab148b1116?w=1#diff-c7c5dc63368698b83764009ffc6713a33d3238d0946b0aa2b87063af89de0551R260 missing a developer mode check
- TODO: Noticed this one is not always true. I noticed it consistently when going up/down planes. Results in Clues being "forgotten"
- https://github.com/Zoinkwiz/clue-details/blob/master/src/main/java/com/cluedetails/ClueGroundManager.java#L167
- https://i.imgur.com/bnf7MjU.gif
=> 2.3.3 Cleanup

src/main/java/com/cluedetails/ClueBankManager.java, src/main/java/com/cluedetails/ClueBankSaveDataManager.java, src/main/java/com/cluedetails/ClueDetailsInventoryOverlay.java, src/main/java/com/cluedetails/ClueDetailsItemsOverlay.java, src/main/java/com/cluedetails/ClueDetailsOverlay.java, src/main/java/com/cluedetails/ClueDetailsPlugin.java, src/main/java/com/cluedetails/ClueDetailsTagsOverlay.java, src/main/java/com/cluedetails/ClueDetailsWidgetsOverlay.java, src/main/java/com/cluedetails/ClueGroundManager.java, src/main/java/com/cluedetails/ClueGroundOverlay.java, src/main/java/com/cluedetails/ClueGroundSaveDataManager.java, src/main/java/com/cluedetails/ClueInventoryManager.java, src/main/java/com/cluedetails/CluePreferenceManager.java, src/main/java/com/cluedetails/ClueThreeStepSaver.java, src/main/java/com/cluedetails/ClueThreeStepSaverWidgetOverlay.java, src/main/java/com/cluedetails/ClueWidgetManager.java, src/main/java/com/cluedetails/Clues.java
It was getting quite messy with all the managers and overlays we were using, and we had some Singletons being potentially instantiated multiple times, and partial injections being used.
=> fix: Cleanup for instantiation of managers and overlays

src/main/java/com/cluedetails/ClueDetailsPlugin.java, src/main/java/com/cluedetails/ClueGroundManager.java
Previous behavior is that all tracked beginner/master clues are forgotten when traversing a plane in render distance of the clues.
Applying this change to all tiers seemed to result in duplication of tracked easy->elite clues.
This change only seems to consistently remember the beginner/master clues once the tile has been fully juggled. If it has not been, all beginner/master clues of that tier are reset to unknown state.
=> fix: Remember beginner/master clues when traversing planes

src/main/java/com/cluedetails/ClueDetailsPlugin.java, src/main/java/com/cluedetails/ClueGroundManager.java, src/main/java/com/cluedetails/WorldPointToClueInstances.java
Addresses ground clue overlay duplication seen when plugin toggled
=> fix: Clear ground clues on restart

src/main/java/com/cluedetails/ClueDetailsPlugin.java, src/main/java/com/cluedetails/ClueGroundManager.java
This allows for easy-elite clues to be renewed should a spawning clue be an old clue (aka we must be loading the tile without a load screen).
=> fix: Avoid duping clues when entering clue area

src/main/java/com/cluedetails/BeginnerMasterClueText.java, src/main/java/com/cluedetails/ClueInventoryManager.java
Previously the user had to read the clue again in order to get the particular step.
Charlie
Falo
=> feat: Identify Charlie & Falo clues from dialogue

src/main/java/com/cluedetails/ClueInstance.java
Using tier  name for unidentified beginner and master clues provides a more cohesive and clean overlay when transitioning between settings
Before: Becomes unclear that the collapsed Beginner is identified
After:
=> feat: Use tier name for unidentified ground clues overlay

src/main/java/com/cluedetails/ClueDetailsConfig.java
Overwrite config items incorrected stated "Does apply to Beginner and Master clues" also clarified they are being applied to the item, since we now have more overlays.
=> fix: Overwrite description

src/main/java/com/cluedetails/ClueDetailsOverlay.java
Submenu order was showing reverse order
Before
After
=> fix: three-step cryptic submenu order

src/main/java/com/cluedetails/ClueDetailsConfig.java, src/main/java/com/cluedetails/ClueGroundOverlay.java
Ability to reverse the overlay to de-conflict with ground items overlay when users do not want to hide clues or want to handle mixed item piles
=> feat: Reverse ground clues overlay

src/main/java/com/cluedetails/ClueWidgetManager.java
Specifically targets Portal Nexus teleports when not using "Better Teleport Menu" plugin which adds "Set hotkey" actions. By default portal nexus teleport menu entries have no actions so they were being skipped.
By enabling "Continue" this will also enable highlighting more options such as dialogue options
=> Allow highlighting widgets with "Continue" option and no actions

src/main/java/com/cluedetails/ClueBankManager.java, src/main/java/com/cluedetails/ClueBankSaveDataManager.java, src/main/java/com/cluedetails/ClueDetailsPlugin.java, src/main/java/com/cluedetails/ClueGroundManager.java, src/main/java/com/cluedetails/ClueGroundOverlay.java, src/main/java/com/cluedetails/ClueGroundSaveDataManager.java, src/main/java/com/cluedetails/ClueInstance.java, src/main/java/com/cluedetails/ClueInstanceData.java, src/main/java/com/cluedetails/WorldPointToClueInstances.java
Currently, despawnTimers per ClueInstance (particularly when used for Ground Clue Timers) "freeze" when not associated with a tileItem
Initial testing did not uncover any issues caused by this change, but please inform of any edge cases I should test.
=> fix: Clue Instance despawn time tracking

src/main/java/com/cluedetails/ClueDetailsInventoryOverlay.java, src/main/java/com/cluedetails/Clues.java
Closes #168
1. Adding `HotColdLocation` values caused `itemIdClueCache` to be populated incorrectly
2. Updated Inventory Overlay to match how `ClueDetailsItemsOverlay` is populated -- respects tier toggles
=> fix: Inventory overlay

src/main/java/com/cluedetails/ClueDetailsPlugin.java, src/main/java/com/cluedetails/ClueGroundManager.java, src/main/java/com/cluedetails/ClueGroundTimer.java
Allows users to clear tracking for world points which they no longer care about and/or may be incorrectly tracked. World points will automatically be added back to tracking if rendered.
Additionally displays "?" for infoboxes with miscalculated despawn times
=> feat: Clear ground clues through timer
